print("COMMANDS")
print(".slock - locks server")
print(".spam - spams text you put after")
print(".unspam - stops spam")
print(".unslock - unlocks server")
print(".gmusic - put number afterwards and play music saved here")
print(".lflood - floods logs")
print(".unlflood - stops flooding the logs")
print(".lg - loopgrab pads")
print(".unlg - unloopgrab pads")
print(".regen - regen the pads")
print(".perm - perm pad")
print(".unperm - unperm pad")
print(".anticrash - stops gear crashing gears")
print(".unanticrash - unstops gear crashing gears")
print(".antigear - bans every gear")
print(".unantigear - unbans gears")
print(".blinder - spam respawn")
print(".unblinder - no spam respawn")
print(".frycam - fries the camera")
print(".fixcam - fixes your camera.") -- BROKEN
print(".house - teleport to the house")
print(".crash - dog/clone crash")
print(".fcrash - freeze crash")
print(".silcrash - dog/clone crash but no blinding, fogends or music")
