local function FireServer(msg)
      game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer(msg)
end
while true do
  FireServer("HEY GUYS!", "All")
  wait(1)
  FireServer("ITS ME, S_P!", "All")
  wait(1)
  FireServer("TODAY WE WILL BE UNBOXING GRANDMA!", "All")
  wait(1)
  FireServer("(GONE WRONG)!", "All")
  wait(1)
  FireServer("DON'T FORGET TO...", "All")
  wait(1)
  FireServer("LIKE!", "All")
  wait(1)
  FireServer("SUBSCRIBE!", "All")
  wait(1)
  FireServer("AND TURN MY DONK ON!", "All")
  wait(1)
  FireServer("PLEASE JOIN MY CHANNEL TOO!", "All")
  wait(1)
  FireServer("IT'S FREE!", "All")
  wait(1)
  FireServer("PLUS 44 DOLLARS", "All")
  wait(1)
  FireServer("CHEAP, IS IT?", "All")
  wait(1)
  FireServer("ANYWAYS...", "All")
  wait(1)
end
