while true do
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("HEY GUYS!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ITS ME, S_P!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("TODAY WE WILL BE UNBOXING MY GRANDMA AT 3AM!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("(GONE WRONG)!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("DON'T FORGET TO...", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("LIKE!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("SUBSCRIBE!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("AND TURN MY DONK ON!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("PLEASE JOIN MY CHANNEL TOO!", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("IT'S FREE!", "All")
  wait(1)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("PLUS 44 DOLLARS", "All")
  wait(2)
  game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("CHEAP, IS IT?", "All")
  wait(2)
  ...", "All")
  wait(10)
end
