while true do
  game.Players:Chat("h HEY GUYS!")
  wait(4)
  game.Players:Chat("h ITS ME, S_P!")
  wait(4)
  game.Players:Chat("h TODAY WE WILL BE UNBOXING MY GRANDMA AT 3AM!")
  wait(4)
  game.Players:Chat("h (GONE WRONG)!")
  wait(4)
  game.Players:Chat("h DON'T FORGET TO...")
  wait(4)
  game.Players:Chat("h LIKE!")
  wait(4)
  game.Players:Chat("h SUBSCRIBE!")
  wait(4)
  game.Players:Chat("h AND TURN MY DONK ON!")
  wait(4)
  game.Players:Chat("h PLEASE JOIN MY CHANNEL TOO!")
  wait(4)
  game.Players:Chat("h IT'S FREE!")
  wait(4)
  game.Players:Chat("h PLUS 44 DOLLARS")
  wait(1)
  game.Players:Chat("h CHEAP, IS IT?")
  wait(4)
  game.Players:Chat("h anyways...")
  wait(4)
end
